title: Paulus Triswandani
SEOTitle: Blog oleh Paulus Triswandani
url: "https://PaulusTriswandani.github.io"
description: "Knowledge is power, Keep hungry, Keep foolish"
keyword: PTblog, PaulusTriswandani, tech, life, coding, programming

markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM

theme: jekyll-theme-architect